##  Numpy array Operations

In [2]:
import numpy as np

In [4]:
arr= np.array([1,2,3,4,5,6,7,8,9,10])
print(" Basic Slicing ", arr[2:7])
print("with step", arr[1: 8: 2])
print("Negative indexing", arr[-3])


 Basic Slicing  [3 4 5 6 7]
with step [2 4 6 8]
Negative indexing 8


In [ ]:
arr_2d = np.array([[1,2,3],
                   [4,5 ,6],
                   [7,8,9]])

print(" Specific element ", arr_2d[1,2])
print("Entire row ", arr_2d[1])
print("Entire row: ", arr_2d[:, 1])# : = represents all rows  

 Specific element  6
Entire row  [4 5 6]
Entire row:  [2 5 8]


## Sorting

In [8]:
unsorted = np.array([3,1, 4, 5,9, 2, 6])
print("Sorted Array", np.sort(unsorted))


arr_2d_unsorted = np.array([[3,1], [1, 2], [2,3]])
print("Sorted @D array by column", np.sort(arr_2d_unsorted, axis =0))

Sorted Array [1 2 3 4 5 6 9]
Sorted @D array by column [[1 1]
 [2 2]
 [3 3]]


## Filter

In [9]:
numbers =  np.array([ 1, 2, 3, 4, 5, 6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)


Even numbers [ 2  4  6  8 10]


## Filter With Mask

In [10]:
mask  = numbers > 5
print("NUmbers greater than 5", numbers[mask])


NUmbers greater than 5 [ 6  7  8  9 10]


## Fancy Indexing vs np.where

In [11]:
indices  = [0, 2, 4]
print("NP where ", numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP Where", numbers[where_result])



NP where  [1 3 5]
(array([5, 6, 7, 8, 9]),)
NP Where [ 6  7  8  9 10]


In [15]:
condition_array = np.where(numbers > 5, numbers*5, numbers)
print(condition_array)



[ 1  2  3  4  5 30 35 40 45 50]


## Adding and Removing Data

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2   # added the value
print(combined)

combined  =  np.concatenate((arr1, arr2))
print(combined)



[5 7 9]
[1 2 3 4 5 6]


## Array Compatibilty

In [4]:
a = np.array([1,2,3])
b = np.array([4, 5,6,7])
c = np.array([7, 8, 9])

print("Compatibility shaped ", a.shape == b.shape)

Compatibility shaped  False


In [ ]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row) )
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new Column \n", with_new_col)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new Column 
 [[1 2 7]
 [3 4 8]]


In [9]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion:", deleted)


Array after deletion: [1 2 4 5]
