##  Numpy array and basics
learn about numpy 

In [2]:
import numpy as np
arr_1d = np.array([1,2 ,3,4,5])
print("1D array:", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array:", arr_2d)


1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [11]:
py_list = [1,2,3]
print("Python list multiplication", py_list* 2)

np_array = np.array([1 ,2 , 3])   # element wise multiplication
print("Python array multiplication", np_array * 2)


import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n List operation time:", time.time() - start)


start = time.time()
np_array = np.arange(100000)*2
print("\n Numpy Operation Time: ", time.time()- start)


Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]

 List operation time: 0.006014347076416016

 Numpy Operation Time:  0.0016655921936035156


Creating Array From Scratch

In [ ]:
zeros = np.zeros((3,4))
print("Zeros array: \n", zeros)

ones = np.ones((2,3))
print("one array \n",ones)

full = np.full((2,2), 7)
print(" full array: \n", full)

random =  np.random.random((2,3))
print("random array: \n", random);


sequence = np.arange(0, 10, 2)
print("sequence array: \n", sequence)

 


Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array 
 [[1. 1. 1.]
 [1. 1. 1.]]
 full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.70684503 0.45255147 0.46488245]
 [0.35747778 0.76149179 0.73068274]]
random array: 
 [0 2 4 6 8]


vector , Matrix and tensor

In [5]:
vector = np.array([1,2,3])
print("vector:", vector)

matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])

print("Matrix", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7 , 8]]])

print("Tensor \n", tensor )



vector: [1 2 3]
Matrix [[1 2 3]
 [4 5 6]]
Tensor 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [9]:
arr = np.array([[1, 2], [3, 4],
                   [5, 6], [7 , "7.9"]])

print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size ", arr.size)
print("DType", arr.dtype)

Shape (4, 2)
Dimension 2
Size  8
DType <U21


## Array Reshaping 

In [22]:
arr = np.arange(12)
print("original Array", arr)

reshaped = arr.reshape((3, 4))
print("\n reshaped array \n", reshaped)


flattened  = reshaped.flatten()
print("\n Flattened array", flattened)


# ravel (returns view , instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transpose array \n", transpose)


original Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshaped array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
